"""GM SoundFont bank tables (from Leeman1982/gm2350 medusa_gm.h,
generated by sf2_to_amy.py alongside the bank in sounds/gm/fonts.bin).

AMY serves the 160 bank presets at preset numbers PRESET_BASE+i
(wave=PCM), streamed from the mmapped `fonts` flash partition.
Use preset_for_program()/preset_for_drum_note() to resolve GM numbers.
"""

PRESET_BASE = 512   # must match GM_PRESET_BASE in src/pcm_gm.h
NUM_PRESETS = 160

# Bank preset index (0..159) for each GM program 0..127.
PROGRAM_PRESET = [
      0,   0,   1,   0,   2,   3,   4,   5,   6,   7,   6,   8,   9,  10,  11,  12,
     13,  14,  15,  16,  17,  18,  19,  17,  20,  21,  22,  23,  24,  25,  26,  27,
     28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
     44,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  57,
     58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
     74,  57,  75,  75,  26,  76,  77,  78,   3,  44,  45,  76,  45,  46,  45,  45,
     77,  79,  80,  20,  45,  81,  49,  23,  82,  83,  84,  85,  86,  87,  36,  88,
     89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
]

# Bank preset index for each GM drum note 0..127 (255 = none).
DRUM_PRESET = [
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 105, 106, 107, 108, 109,
    110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 119, 121, 122, 123, 124,
    125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 128, 136, 137, 138, 139,
    140, 141, 142,  90,  90, 143, 144, 145, 146, 147, 148, 149,  92,  92, 150, 151,
    152, 153, 154, 155, 156, 157, 158, 159, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
]

# Recorded root MIDI note of each preset. Melodic notes pitch relative
# to it; play drums at their root for natural pitch.
PRESET_ROOT = [
     60,  60,  55,  60,  65,  57,  63,  80,  62,  60,  76,  72,  67,  53,  89,  72,
     58,  62,  58,  64,  72,  59,  60,  59,  63,  60,  59,  67,  64,  69,  57,  56,
     57,  41,  57,  51,  59,  60,  59,  64,  57,  56,  60,  50,  60,  60,  69,  59,
     69,  61,  76,  58,  62,  46,  62,  63,  60,  57,  73,  62,  62,  66,  61,  61,
     60,  58,  82,  61,  62,  81,  54,  72,  66,  73,  57,  62,  60,  60,  57,  84,
     64,  72,  55,  66,  70,  57,  68,  94,  70, 102,  72,  60,  60,  60,  60,  60,
     60,  69,  61,  60,  60,  60,  60,  60,  60,  45,  40,  29,  30,  31,  60,  44,
     45,  35,  36,  37,  60,  54,  38,  42,  42,  53,  45,  46,  47,  48,  49,  50,
     51,  58,  53,  66,  55,  61,  57,  58,  74,  73,  67,  63,  69,  70,  66,  70,
     69,  71,  72,  73,  74,  75,  78,  79,  93,  94,  82,  83,  84,  85,  86,  87,
]

# 1 = preset has a sustain loop (send feedback=1, or >=2 for
# sustain-through-release); 0 = one-shot.
PRESET_LOOPED = [
      0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   0,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   0,   1,   1,   1,   0,   0,   1,   0,   0,   1,   1,   1,
      1,   1,   0,   1,   1,   1,   1,   1,   0,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   0,   0,   1,   0,   1,   1,   1,   1,   1,   1,
      1,   1,   0,   1,   1,   1,   1,   1,   1,   1,   0,   1,   0,   1,   0,   0,
      0,   0,   0,   1,   0,   1,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   1,
      0,   1,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   0,   0,   0,   0,   0,   0,
]

# GM program names for UIs.
NAMES = [
    'Grand Piano', 'Bright Grand', 'Electric Gra', 'Honky-Tonk P',
    'Tine Electri', 'FM Electric ', 'Harpsichord', 'Clavinet',
    'Celeste', 'Glockenspiel', 'Music Box', 'Vibraphone',
    'Marimba', 'Xylophone', 'Tubular Bell', 'Dulcimer',
    'Tonewheel Or', 'Percussive O', 'Rock Organ', 'Pipe Organ',
    'Reed Organ', 'Accordion', 'Harmonica', 'Bandoneon',
    'Nylon Guitar', 'Steel Guitar', 'Jazz Guitar', 'Clean Guitar',
    'Muted Guitar', 'Overdrive Gu', 'Distortion G', 'Guitar Harmo',
    'Acoustic Bas', 'Finger Bass', 'Pick Bass', 'Fretless Bas',
    'Slap Bass 1', 'Slap Bass 2', 'Synth Bass 1', 'Synth Bass 2',
    'Violin', 'Viola', 'Cello', 'Double Bass',
    'Tremolo Stri', 'Pizzicato St', 'Orchestral H', 'Timpani',
    'Fast Strings', 'Slow Strings', 'Synth String', 'Synth String',
    'Concert Choi', 'Voice Oohs', 'Synth Voice', 'Orchestra Hi',
    'Trumpet', 'Trombone', 'Tuba', 'Muted Trumpe',
    'French Horns', 'Brass Sectio', 'Synth Brass ', 'Synth Brass ',
    'Soprano Sax', 'Alto Sax', 'Tenor Sax', 'Baritone Sax',
    'Oboe', 'English Horn', 'Bassoon', 'Clarinet',
    'Piccolo', 'Flute', 'Recorder', 'Pan Flute',
    'Bottle Blow', 'Shakuhachi', 'Whistle', 'Ocarina',
    'Square Lead', 'Saw Lead', 'Synth Callio', 'Chiffer Lead',
    'Charang', 'Solo Vox', '5th Saw Wave', 'Bass & Lead',
    'Fantasia', 'Warm Pad', 'Polysynth', 'Space Voice',
    'Bowed Glass', 'Metal Pad', 'Halo Pad', 'Sweep Pad',
    'Ice Rain', 'Soundtrack', 'Crystal', 'Atmosphere',
    'Brightness', 'Goblin', 'Echo Drops', 'Star Theme',
    'Sitar', 'Banjo', 'Shamisen', 'Koto',
    'Kalimba', 'Bagpipes', 'Fiddle', 'Shenai',
    'Tinker Bell', 'Agogo', 'Steel Drums', 'Wood Block',
    'Taiko Drum', 'Melodic Tom', 'Synth Drum', 'Reverse Cymb',
    'Fret Noise', 'Breath Noise', 'Seashore', 'Birds',
    'Telephone 1', 'Helicopter', 'Applause', 'Gun Shot',
]


def preset_for_program(program):
    """AMY preset number for GM program 0..127."""
    return PRESET_BASE + PROGRAM_PRESET[program]


def preset_for_drum_note(note):
    """AMY preset number for a GM drum-channel note, or None."""
    p = DRUM_PRESET[note]
    return None if p == 255 else PRESET_BASE + p


# --- deck-side helpers -------------------------------------------------------

def name(program):
    """UI name for GM program 0..127."""
    return NAMES[program]


def patch_string(program):
    """AMY patch wire string for a GM program, for PatchSynth(patch_string=).

    wave=PCM (w7) + the bank preset, feedback=2 for sustain-through-release
    (note-off hands the voice to the amp EG instead of cutting the sample).
    Looped presets sustain like an organ and get a musical release; one-shots
    get a long-release EG so they ring to their natural end.
    """
    pi = PROGRAM_PRESET[program]
    preset = PRESET_BASE + pi
    if PRESET_LOOPED[pi]:
        eg = "A5,1,60000,0.85,220,0"   # fast attack, slow settle, 220ms release
    else:
        eg = "A0,1,30000,1,4000,0"     # one-shot: EG never chokes the sample
    return "v0w7p%db2%sZ" % (preset, eg)
