"""FX values baked into the AMY patch strings (generated from amy
src/patches.h by scratchpad gen_patchfx.py). A loaded patch SETS
these in AMY itself; this table lets the deck's FX editor show the
values the patch actually applied (and layer user edits on top)
instead of pretending everything is 0. Regenerate when patches.h
changes."""

FX = {
    0: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    1: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    2: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    3: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    4: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    5: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    6: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    7: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    8: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    9: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    10: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    11: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    12: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    14: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    15: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    17: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    18: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    19: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    20: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    21: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    22: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    23: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    24: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    25: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    26: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    27: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    28: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    29: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    30: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    31: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    32: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    33: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    34: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    35: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    36: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    37: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    38: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    39: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    40: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    41: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    42: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    43: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    44: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    45: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    46: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    47: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    48: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    49: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    50: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    51: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    52: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    53: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    54: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    55: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    56: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    57: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    59: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    60: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    61: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    62: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    63: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    64: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    65: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    66: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    67: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    68: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    69: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    70: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    71: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    72: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    73: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    74: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    75: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    76: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    77: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    78: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    79: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    80: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    81: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    82: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    83: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    84: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    85: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    86: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    87: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    88: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    89: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    90: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    91: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    92: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    93: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    94: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    95: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    96: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    97: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    98: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    99: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    100: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    101: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    102: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    103: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    104: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    105: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    106: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    107: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    108: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    109: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    110: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    111: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    112: {'eq': {'low': -8, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    113: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    114: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    115: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    116: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 0}},
    117: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    118: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    119: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    120: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    121: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    122: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    123: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    124: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 1, 'freq': 0.83, 'depth': 0.5}},
    125: {'eq': {'low': -15, 'mid': 8, 'high': 8}, 'chorus': {'level': 1, 'freq': 0.5, 'depth': 0.5}},
    126: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0}},
    127: {'eq': {'low': 7, 'mid': -3, 'high': -3}, 'chorus': {'level': 0}},
    256: {'chorus': {'level': 0}},
    257: {'eq': {'low': 0, 'mid': 0, 'high': 0}, 'chorus': {'level': 0, 'freq': 0.5, 'depth': 0.5}},
}


def patch_fx(patch):
    """FX dict a baked patch applies ({} for none/unknown)."""
    return FX.get(patch, {})
