# synthkits.py -- synthesized drum kits (DrumSynth-derived + Synth-Secrets
# recipes), the TR-8S-style alternative to the sampled Gamma9001 kits.
#
# Data lives in synthkits.json (generated by tools/drumsynth/make_synthkits.py
# from 1,000+ harvested .ds patches): a corpus of HITS (each <= 2 AMY oscs:
# tone + noise) and KITS mapping GM drum notes to hit keys. Each hit becomes
# its own tiny AMY synth at kit load, so per-hit sound design (tune/decay/
# level/snap) is just re-sending one synth's patch string -- no engine work.
#
# Import-clean on CPython (tulip/amy imported lazily) so tests can run on the
# host against the same JSON.

import json

# Split data layout (v2): synthkits_data/index.json (NOT 'synthkits/'
# -- a directory of that name shadows this module in MicroPython's import) = kits + pack listings + hit
# names (small, parsed once); synthkits/<pack>.json = that pack's hit params,
# loaded on demand. The old single 279KB file starved the UI task on-device
# (watchdog reset) while parsing.
_DIRS = ('/user/synthkits_data', 'synthkits_data')
_state = {'index': None, 'dir': None, 'packs': {}}

# Deck-wide RAM-patch SLOT MAP (user patches 1024+). AMY stores every
# patch_string into a RAM slot and slots are never freed -- sending raw
# patch_string on each router rebuild leaked the pool dry. Deck code stores
# at EXPLICIT numbers instead (stores overwrite), then loads by number:
#   1024        audition scratch (this module)
#   1025..1029  melodic patch_string instruments by creation order (forwarder)
#   1030+24*n   drum kit instance n: kit patch at base, hits at base+1..
SLOT_AUDITION = 1024
SLOT_MELODIC = 1025
SLOT_KITS = 1030
SLOT_KIT_STRIDE = 24
# Hard bounds (E-4). AMY caps user patches at max_memory_patches=128
# (amy_connector.c) -> valid slots are 1024..1151. Without these caps the
# 6th melodic instrument would store into the first kit's window and the
# 6th kit would walk past 1151 into AMY's rejection range -- both present
# as "wrong sounds on another instrument".
MAX_MELODIC_SLOTS = SLOT_KITS - SLOT_MELODIC          # 5
MAX_KIT_SLOTS = (1024 + 128 - SLOT_KITS) // SLOT_KIT_STRIDE   # 5
SLOT_LIMIT = 1024 + 128


def store_patch(slot, patch_string):
    """Store a patch string at an explicit reusable RAM slot."""
    import amy
    amy.send(patch=slot, patch_string=patch_string)
    return slot

# wire letters per osc kwarg (see amy parse.c); order chosen so envelopes
# arrive before amp
_WIRE = (('wave', 'w'), ('freq', 'f'), ('duty', 'd'), ('phase', 'P'),
         ('bp1', 'B'), ('bp0', 'A'), ('amp', 'a'), ('filter_type', 'G'),
         ('filter_freq', 'F'), ('resonance', 'R'))

# Per-osc filter reset defaults (AMY: reset_osc -> filter_type FILTER_NONE=0,
# resonance 0.7; see amy.c). AMY recycles a RELEASED voice's oscs WITHOUT
# clearing per-osc params, so any filter a patch string OMITS persists from
# whatever last played on that voice. The pad picker auditions every hit on
# the SAME scratch synth (17), so a plain hit auditioned right after a
# filtered one (e.g. an HPF@9400 hi-hat) inherited the cutoff and rendered
# near-silent. Emitting these for every osc that leaves a filter param out
# makes each patch string self-contained -- a recycled voice starts clean.
# (F0/G0 = filter fully off; F is irrelevant once G0 but reset for good
# measure so a leaked cutoff can't matter.)
_FILTER_RESET = (('filter_type', 0), ('filter_freq', 0), ('resonance', 0.7))


def _load():
    if _state['index'] is None:
        for d in _DIRS:
            try:
                with open(d + '/index.json') as f:
                    _state['index'] = json.load(f)
                _state['dir'] = d
                break
            except (OSError, ValueError):
                continue
        if _state['index'] is None:
            _state['index'] = {'kits': {}, 'packs': {}, 'names': {}}
    return _state['index']


def _hit(hit_key):
    pack = hit_key.split('/', 1)[0]
    ph = _state['packs'].get(pack)
    if ph is None:
        _load()
        try:
            with open('%s/%s.json' % (_state['dir'], pack)) as f:
                ph = json.load(f)
        except (OSError, ValueError, TypeError):
            ph = {}
        _state['packs'][pack] = ph
    return ph.get(hit_key)


def kits():
    """{kit_key: display name}."""
    return {k: v['name'] for k, v in _load()['kits'].items()}


def kit_notes(kit_key):
    """{midi_note(int): hit_key} for a kit -- the kit's REAL pads."""
    kits_ = _load()['kits']
    k = kits_.get(kit_key)
    if k is None and len(kit_key) > 2 and kit_key[-2] == '_' \
            and 'a' <= kit_key[-1] <= 'z':
        # Variant kits ('tr909_d') come and go across data regenerations (the
        # generator dedupes near-identical kits away), but saved configs keep
        # referencing them -- an unknown key returned {} and the instrument went
        # SILENTLY dead. Fall back to the variant's base kit.
        k = kits_.get(kit_key[:-2])
    return {int(n): h for n, h in k['notes'].items()} if k else {}


# The sampled kits (AMY patches 384-390) bake note-map entries across nearly
# the whole GM percussion range, so any key plays something. Synth kits map
# only their 5-20 real pads -- one hit every ~5 keys, dead outside. gm_fill
# closes that gap by ALIASING every unmapped note to its nearest real pad.
GM_LO, GM_HI = 35, 81   # GM percussion range the sampled kits cover


def gm_fill(notes):
    """{gm_note: base_note} covering GM_LO..GM_HI: mapped notes map to
    themselves, unmapped notes alias the NEAREST mapped note (tie -> lower).
    notes: iterable of int mapped notes. Empty input -> {}."""
    mapped = sorted(notes)
    if not mapped:
        return {}
    out = {}
    for n in range(GM_LO, GM_HI + 1):
        best = mapped[0]
        bd = abs(n - best)
        for m in mapped[1:]:            # ascending -> ties keep the LOWER note
            d = abs(n - m)
            if d < bd:
                best, bd = m, d
        out[n] = best
    return out


def hit_name(hit_key):
    name = _load()['names'].get(hit_key, hit_key)
    # strip trailing dedup-hash suffixes ('brush1_139732', 'kick_7dbbaa')
    # from DISPLAY -- engineering artifacts, not names (fresh-eyes F-8);
    # the raw key stays the lookup identity
    i = name.rfind('_')
    if i > 0:
        tail = name[i + 1:]
        # Only strip the generator's dedup hash, which is ALWAYS exactly 6 hex
        # chars (make_synthkits.classify: \b[0-9a-f]{6}\b). The old >=4 test
        # swallowed legit numeric/hex-word suffixes ('kick_1200', 'snare_9090',
        # 'x_face') too, merging distinct hits to one display name (F-8).
        if len(tail) == 6 and all(c in '0123456789abcdef' for c in tail):
            name = name[:i]
    return name


def pack_hits(pack):
    """Every hit key in a pack (for the picker/editor's alternates list)."""
    return list(_load()['packs'].get(pack, []))


def _fmt(x):
    if isinstance(x, str):
        return x
    if abs(x - round(x)) < 0.005:
        return '%d' % round(x)
    return ('%.3f' % x).rstrip('0').rstrip('.')


def _scale_times(bp, factor):
    """Scale a bp string's TIME entries (even slots) by factor."""
    vals = bp.split(',')
    out = []
    for i, v in enumerate(vals):
        if i % 2 == 0:
            try:
                out.append('%d' % max(0, round(float(v) * factor)))
            except ValueError:
                out.append(v)
        else:
            out.append(v)
    return ','.join(out)


def _scale_first(csv, factor):
    """Scale the first (const) slot of a coef string."""
    vals = csv.split(',')
    try:
        vals[0] = _fmt(float(vals[0]) * factor)
    except ValueError:
        pass
    return ','.join(vals)


# Synth hits are built at design amplitudes <=1.0 while the sampled kits'
# baked map entries run 3..13 -- measured on device the same kick line
# peaked 0.906 (sampled '80s Power) vs 0.159 (tr909_d). This closes the gap;
# the per-hit 'level' override still scales on top of it. Capped: 4x drove
# resonant-filter hits into fixed-point saturation that LATCHED (a pad rang
# forever at full level until the router rebuilt).
KIT_GAIN = 2.5
_AMP_CAP = 2.5


def _capped_gain(csv, g):
    """Scale a coef string's const slot by g, hard-capped at _AMP_CAP."""
    vals = csv.split(',')
    try:
        vals[0] = _fmt(min(_AMP_CAP, float(vals[0]) * g))
    except ValueError:
        pass
    return ','.join(vals)


def _xform_partials(ps, tune, decay, level):
    """Apply tune/decay/level to a prebuilt BYO_PARTIALS patch string:
    children (w9) get their partial freq scaled by tune and bp times by
    decay; ONLY the parent (w10) amp is scaled by level (children multiply
    through the parent, scaling both would square the gain)."""
    out = []
    for frag in ps.split('Z'):
        if not frag:
            continue
        toks, key, val = [], None, ''
        for ch in frag:
            if ch.isalpha() and ch in 'vwpfadPABGFR':
                if key is not None:
                    toks.append((key, val))
                key, val = ch, ''
            else:
                val += ch
        if key is not None:
            toks.append((key, val))
        present = dict(toks)
        wave = present.get('w')
        nf = []
        for k, v in toks:
            if k == 'f' and tune != 1.0 and wave == '9':
                v = _scale_first(v, tune)
            elif k == 'a' and level != 1.0 and wave == '10':
                v = _capped_gain(v, level)
            elif k in 'AB' and decay != 1.0:
                v = _scale_times(v, decay)
            nf.append(k + v)
        # self-contained filter state (same recycled-voice leak as the wire
        # path above): reset any filter letter this osc omits so a partials
        # hit auditioned after a filtered one can't inherit its cutoff.
        for key, letter in (('G', 'filter_type'), ('F', 'filter_freq'),
                            ('R', 'resonance')):
            if key not in present:
                nf.append(key + _fmt(dict(_FILTER_RESET)[letter]))
        out.append(''.join(nf))
    return 'Z'.join(out) + 'Z'


def hit_patch_string(hit_key, overrides=None):
    """AMY patch wire string for one hit ('v0...Zv1...Z'), with sound-design
    overrides applied: tune (semitones, +/-24), decay (0.25..4 time scale),
    level (0..2 gain), snap (0..2 gain on the noise/transient osc)."""
    hit = _hit(hit_key)
    if hit is None:
        raise KeyError(hit_key)
    ov = overrides or {}
    tune = 2.0 ** (max(-24.0, min(24.0, float(ov.get('tune', 0)))) / 12.0)
    decay = max(0.25, min(4.0, float(ov.get('decay', 1.0))))
    level = max(0.0, min(2.0, float(ov.get('level', 1.0)))) * KIT_GAIN
    snap = max(0.0, min(2.0, float(ov.get('snap', 1.0))))
    if 'patch_string' in hit:
        # partials-resynthesized hit: transform the prebuilt string in place
        return _xform_partials(hit['patch_string'], tune, decay, level)
    parts = []
    for i, osc in enumerate(hit['oscs'][:2]):
        o = dict(osc)
        if 'freq' in o and tune != 1.0:
            o['freq'] = _scale_first(o['freq'], tune)
        if 'filter_freq' in o and tune != 1.0:
            o['filter_freq'] = _scale_first(str(o['filter_freq']), tune)
        if decay != 1.0:
            for bp in ('bp0', 'bp1'):
                if bp in o:
                    o[bp] = _scale_times(o[bp], decay)
        g = level * (snap if o.get('wave') == 5 else 1.0)   # 5 = NOISE
        if g != 1.0 and 'amp' in o:
            o['amp'] = _capped_gain(o['amp'], g)
        # make the osc self-contained: fill any omitted filter param with its
        # reset default so a recycled voice can't inherit a prior hit's filter
        for key, dflt in _FILTER_RESET:
            if key not in o:
                o[key] = dflt
        frag = ['v%d' % i]
        for key, letter in _WIRE:
            if key in o:
                frag.append(letter + _fmt(o[key]))
        parts.append(''.join(frag))
    return 'Z'.join(parts) + 'Z'


def audition(hit_key, overrides=None, note=60, vel=1.0, synth=17):
    """Play one hit immediately (editor preview). Uses scratch synth 17 --
    ABOVE the MIDI-channel range: 15 destroyed and re-patched a C-owned
    channel-15 instrument whenever the pad editor auditioned (review F-8).
    (patch_string implies the osc count -- passing oscs_per_voice alongside
    it makes AMY ignore the stored patch.)"""
    import amy
    store_patch(SLOT_AUDITION, hit_patch_string(hit_key, overrides))
    amy.send(synth=synth, num_voices=0)   # release: a re-patch on a live
    amy.send(synth=synth, num_voices=1,   # synth keeps its old config
             patch=SLOT_AUDITION)
    amy.send(synth=synth, note=note, vel=vel)
