# synthkits.py -- synthesized drum kits (DrumSynth-derived + Synth-Secrets
# recipes), the TR-8S-style alternative to the sampled Gamma9001 kits.
#
# Data lives in synthkits.json (generated by tools/drumsynth/make_synthkits.py
# from 1,000+ harvested .ds patches): a corpus of HITS (each <= 2 AMY oscs:
# tone + noise, plus a few partials-resynthesized ones) and KITS mapping GM
# drum notes to hit keys. A kit loads as ONE container synth (kit_container:
# every hit an osc block in a single patch, upstream 384-390 style); per-hit
# sound design (tune/decay/level/snap) re-sends just that hit's osc params to
# the live synth -- no engine work.
#
# Import-clean on CPython (tulip/amy imported lazily) so tests can run on the
# host against the same JSON.

import json

# Split data layout (v2): synthkits_data/index.json (NOT 'synthkits/'
# -- a directory of that name shadows this module in MicroPython's import) = kits + pack listings + hit
# names (small, parsed once); synthkits/<pack>.json = that pack's hit params,
# loaded on demand. The old single 279KB file starved the UI task on-device
# (watchdog reset) while parsing.
_DIRS = ('/user/synthkits_data', 'synthkits_data')
_state = {'index': None, 'dir': None, 'packs': {}}

# Deck-wide RAM-patch SLOT MAP (user patches 1024+). AMY stores every
# patch_string into a RAM slot and slots are never freed -- sending raw
# patch_string on each router rebuild leaked the pool dry. Deck code stores
# at EXPLICIT numbers instead (stores overwrite), then loads by number:
#   1024        audition scratch (this module)
#   1025..1029  melodic patch_string instruments by creation order (forwarder)
#   1030+6*n    drum kit instance n: CONTAINER patch at base (the whole kit as
#               one voice, upstream 384-390 style), base+1.. for the rare
#               fallback pads that can't be expressed as container oscs
SLOT_AUDITION = 1024
SLOT_MELODIC = 1025
SLOT_KITS = 1030
# Container migration: a synth kit is ONE patch (all hits as consecutive osc
# blocks) + osc-targeted note maps, so a kit needs 1 slot, not 1030+24*n's
# per-hit window. The stride keeps 5 spare slots per kit for fallback pads
# (hits classify_hit() can't place in the container -- none in the current
# corpus, headroom for future data regens).
SLOT_KIT_STRIDE = 6
# Hard bounds (E-4). AMY caps user patches at max_memory_patches=128
# (amy_connector.c) -> valid slots are 1024..1151. Without these caps the
# 6th melodic instrument would store into the first kit's window and a kit
# past MAX_KIT_SLOTS would walk past 1151 into AMY's rejection range -- both
# present as "wrong sounds on another instrument".
MAX_MELODIC_SLOTS = SLOT_KITS - SLOT_MELODIC          # 5
MAX_KIT_SLOTS = (1024 + 128 - SLOT_KITS) // SLOT_KIT_STRIDE   # 20
SLOT_LIMIT = 1024 + 128


# amy.h RESET_PATCH: clear one stored RAM patch's delta list
RESET_PATCH = 524288


def store_patch(slot, patch_string):
    """Store a patch string at an explicit reusable RAM slot. The slot is
    RESET first: AMY's store APPENDS deltas to whatever the slot already
    holds (patches_store_patch never frees the old list), so an un-reset
    overwrite grows the list forever and replays stale params on the next
    load -- for a kit container (hundreds of deltas) that leak compounds on
    every rebuild."""
    import amy
    amy.send(reset=RESET_PATCH, patch=slot)
    amy.send(patch=slot, patch_string=patch_string)
    return slot

# wire letters per osc kwarg (see amy parse.c); order chosen so envelopes
# arrive before amp
_WIRE = (('wave', 'w'), ('freq', 'f'), ('duty', 'd'), ('phase', 'P'),
         ('bp1', 'B'), ('bp0', 'A'), ('amp', 'a'), ('filter_type', 'G'),
         ('filter_freq', 'F'), ('resonance', 'R'))

# Per-osc filter reset defaults (AMY: reset_osc -> filter_type FILTER_NONE=0,
# resonance 0.7; see amy.c). AMY recycles a RELEASED voice's oscs WITHOUT
# clearing per-osc params, so any filter a patch string OMITS persists from
# whatever last played on that voice. The pad picker auditions every hit on
# the SAME scratch synth (17), so a plain hit auditioned right after a
# filtered one (e.g. an HPF@9400 hi-hat) inherited the cutoff and rendered
# near-silent. Emitting these for every osc that leaves a filter param out
# makes each patch string self-contained -- a recycled voice starts clean.
# (F0/G0 = filter fully off; F is irrelevant once G0 but reset for good
# measure so a leaked cutoff can't matter.)
_FILTER_RESET = (('filter_type', 0), ('filter_freq', 0), ('resonance', 0.7))


def _load():
    if _state['index'] is None:
        for d in _DIRS:
            try:
                with open(d + '/index.json') as f:
                    _state['index'] = json.load(f)
                _state['dir'] = d
                break
            except (OSError, ValueError):
                continue
        if _state['index'] is None:
            _state['index'] = {'kits': {}, 'packs': {}, 'names': {}}
    return _state['index']


def _hit(hit_key):
    pack = hit_key.split('/', 1)[0]
    ph = _state['packs'].get(pack)
    if ph is None:
        _load()
        try:
            with open('%s/%s.json' % (_state['dir'], pack)) as f:
                ph = json.load(f)
        except (OSError, ValueError, TypeError):
            ph = {}
        _state['packs'][pack] = ph
    return ph.get(hit_key)


def kits():
    """{kit_key: display name}."""
    return {k: v['name'] for k, v in _load()['kits'].items()}


def kit_notes(kit_key):
    """{midi_note(int): hit_key} for a kit -- the kit's REAL pads."""
    kits_ = _load()['kits']
    k = kits_.get(kit_key)
    if k is None and len(kit_key) > 2 and kit_key[-2] == '_' \
            and 'a' <= kit_key[-1] <= 'z':
        # Variant kits ('tr909_d') come and go across data regenerations (the
        # generator dedupes near-identical kits away), but saved configs keep
        # referencing them -- an unknown key returned {} and the instrument went
        # SILENTLY dead. Fall back to the variant's base kit.
        k = kits_.get(kit_key[:-2])
    return {int(n): h for n, h in k['notes'].items()} if k else {}


# The sampled kits (AMY patches 384-390) bake note-map entries across nearly
# the whole GM percussion range, so any key plays something. Synth kits map
# only their 5-20 real pads -- one hit every ~5 keys, dead outside. gm_fill
# closes that gap by ALIASING every unmapped note to its nearest real pad.
GM_LO, GM_HI = 35, 81   # GM percussion range the sampled kits cover


def gm_fill(notes):
    """{gm_note: base_note} covering GM_LO..GM_HI: mapped notes map to
    themselves, unmapped notes alias the NEAREST mapped note (tie -> lower).
    notes: iterable of int mapped notes. Empty input -> {}."""
    mapped = sorted(notes)
    if not mapped:
        return {}
    out = {}
    for n in range(GM_LO, GM_HI + 1):
        best = mapped[0]
        bd = abs(n - best)
        for m in mapped[1:]:            # ascending -> ties keep the LOWER note
            d = abs(n - m)
            if d < bd:
                best, bd = m, d
        out[n] = best
    return out


def pack_fill(notes):
    """{played_note: (home_note, shift_semitones)} tiling the packed block of
    distinct hits across the whole GM_LO..GM_HI percussion range.

    The base block packs the sorted distinct home-notes onto ADJACENT keys from
    the anchor (min home-note) up: anchor+i plays the i-th home-note, shift 0.
    That block then REPEATS to fill the range: each repetition up the keyboard
    adds +12 semitones (one octave) of pitch, and -- when the anchor sits above
    GM_LO -- one -12 repetition fills the keys below the anchor. shift is
    clamped to +/-24 (the container freq-rewrite range), so far-flung octaves
    saturate rather than detune into noise.

    Every GM percussion key now sounds (the sampled kits' whole-range contract),
    one distinct hit per key, pitched by whole octaves away from home -- unlike
    gm_fill's nearest-pad aliasing, where one pad beside a big gap wins half the
    keyboard. The base block (shift 0) is bit-identical to the old compact map,
    so an unshifted key renders exactly as before. Empty input -> {}."""
    home = sorted(set(notes))
    if not home:
        return {}
    n = len(home)
    anchor = home[0]                    # == min(home_notes)
    out = {}
    b = -1 if anchor > GM_LO else 0     # one octave-down block below the anchor
    while True:
        base = anchor + b * n
        if base > GM_HI:
            break
        shift = max(-24, min(24, 12 * b))
        for i, h in enumerate(home):
            played = base + i
            if GM_LO <= played <= GM_HI:
                out[played] = (h, shift)
        b += 1
    return out


def hit_name(hit_key):
    name = _load()['names'].get(hit_key, hit_key)
    # strip trailing dedup-hash suffixes ('brush1_139732', 'kick_7dbbaa')
    # from DISPLAY -- engineering artifacts, not names (fresh-eyes F-8);
    # the raw key stays the lookup identity
    i = name.rfind('_')
    if i > 0:
        tail = name[i + 1:]
        # Only strip the generator's dedup hash, which is ALWAYS exactly 6 hex
        # chars (make_synthkits.classify: \b[0-9a-f]{6}\b). The old >=4 test
        # swallowed legit numeric/hex-word suffixes ('kick_1200', 'snare_9090',
        # 'x_face') too, merging distinct hits to one display name (F-8).
        if len(tail) == 6 and all(c in '0123456789abcdef' for c in tail):
            name = name[:i]
    return name


def pack_hits(pack):
    """Every hit key in a pack (for the picker/editor's alternates list)."""
    return list(_load()['packs'].get(pack, []))


def _fmt(x):
    if isinstance(x, str):
        return x
    if abs(x - round(x)) < 0.005:
        return '%d' % round(x)
    return ('%.3f' % x).rstrip('0').rstrip('.')


def _scale_times(bp, factor):
    """Scale a bp string's TIME entries (even slots) by factor."""
    vals = bp.split(',')
    out = []
    for i, v in enumerate(vals):
        if i % 2 == 0:
            try:
                out.append('%d' % max(0, round(float(v) * factor)))
            except ValueError:
                out.append(v)
        else:
            out.append(v)
    return ','.join(out)


def _scale_first(csv, factor):
    """Scale the first (const) slot of a coef string."""
    vals = csv.split(',')
    try:
        vals[0] = _fmt(float(vals[0]) * factor)
    except ValueError:
        pass
    return ','.join(vals)


# Container hits pitch by keyboard octave (pack_fill's shift): the note map
# fires the hit at note 60+shift, so the hit's freq must track the note. AMY:
#   logfreq = const + note_coef*(note-69)/12       (const in Hz, log-zero 440Hz)
# Today container hits bake note_coef 0 (note-independent, every key same pitch).
# Setting note_coef 1 and const *= 2**(9/12) keeps note 60 BIT-IDENTICAL to the
# old value -- const*2**(9/12) * 2**((60-69)/12) == const -- while note 60+k
# renders +k semitones. 9/12 because the map fires at 60, nine semitones below
# the 69 log-zero.
_PITCH_OCT = 2.0 ** (9.0 / 12.0)


def _pitch_freq(csv):
    """Rewrite a freq coef string so the played note drives pitch (see
    _PITCH_OCT). const slot *= 2**(9/12); note-coef slot (1) := 1."""
    vals = csv.split(',')
    try:
        vals[0] = _fmt(float(vals[0]) * _PITCH_OCT)
    except (ValueError, IndexError):
        return csv
    while len(vals) < 2:
        vals.append('0')
    vals[1] = '1'
    return ','.join(vals)


# Synth hits are built at design amplitudes <=1.0 while the sampled kits'
# baked map entries run 3..13 -- measured on device the same kick line
# peaked 0.906 (sampled '80s Power) vs 0.159 (tr909_d). This closes the gap;
# the per-hit 'level' override still scales on top of it.
#
# 1.5 (was 2.5): recalibrated against the CAPPED sampled kits (kitcaps.py drops
# their peaks to ~1.25 FS). At 1.5 the tr808 synth kick renders 1.09 FS, at
# parity with juno's 1.03 and the capped sampled kicks (levels/#96). 2.5 sat a
# whole octave hotter than the reference once the sampled kits stopped clipping.
KIT_GAIN = 1.5
# _AMP_CAP stays 2.5 and does NOT track KIT_GAIN: it is a RENDER-time guard, not
# a loudness knob. It bounds the fixed-point amp*velscale product at ~2.5, the
# point past which resonant-filter hits drove AMY into a saturation latch (a pad
# rang forever at full level until the router rebuilt). That threshold is a
# property of the engine's fixed-point math, independent of how KIT_GAIN is
# calibrated -- lowering it with KIT_GAIN would re-arm the trim on hits the
# engine renders cleanly. At KIT_GAIN 1.5 the default product rarely reaches it.
_AMP_CAP = 2.5


def _capped_gain(csv, g, cap=_AMP_CAP):
    """Scale a coef string's const slot by g, hard-capped at cap."""
    vals = csv.split(',')
    try:
        vals[0] = _fmt(min(cap, float(vals[0]) * g))
    except ValueError:
        pass
    return ','.join(vals)


def _xform_partials(ps, tune, decay, level, amp_cap=_AMP_CAP, base_osc=0,
                    pitch=False):
    """Apply tune/decay/level to a prebuilt BYO_PARTIALS patch string:
    children (w9) get their partial freq scaled by tune and bp times by
    decay; ONLY the parent (w10) amp is scaled by level (children multiply
    through the parent, scaling both would square the gain). amp_cap bounds
    the parent amp (the container path passes _AMP_CAP/velscale so the
    render-time amp*velocity product replicates the legacy amp cap).
    base_osc renumbers the fragments (v0->v<base_osc>..) so the hit can sit
    inside a kit container patch.

    pitch=True makes the PARENT track the played note (container path only):
    the note map fires the whole cluster at note 60+shift and each child's
    logfreq = child_const + parent_logfreq (interp_partials.c), so pitching the
    parent transposes every partial. The parent carries no freq of its own, so
    one is inserted at the pitched default (see _pitch_freq / _PITCH_OCT); at
    note 60 it is a no-op (bit-identical to today). Children stay unpitched --
    they ride the parent."""
    out = []
    for frag in ps.split('Z'):
        if not frag:
            continue
        toks, key, val = [], None, ''
        for ch in frag:
            if ch.isalpha() and ch in 'vwpfadPABGFR':
                if key is not None:
                    toks.append((key, val))
                key, val = ch, ''
            else:
                val += ch
        if key is not None:
            toks.append((key, val))
        present = dict(toks)
        wave = present.get('w')
        nf = []
        for k, v in toks:
            if k == 'v' and base_osc:
                v = '%d' % (int(v) + base_osc)
            elif k == 'f' and pitch and wave == '10':
                v = _pitch_freq(v)         # parent already carries a freq
            elif k == 'f' and tune != 1.0 and wave == '9':
                v = _scale_first(v, tune)
            elif k == 'a' and wave == '10' and (level != 1.0
                                                or amp_cap != _AMP_CAP):
                v = _capped_gain(v, level, amp_cap)
            elif k in 'AB' and decay != 1.0:
                v = _scale_times(v, decay)
            nf.append(k + v)
        # Pitch a parent that has NO freq of its own: insert one at the pitched
        # 440Hz default (note-coef 1) so the note transposes the cluster.
        if pitch and wave == '10' and 'f' not in present:
            nf.append('f' + _pitch_freq('440'))
        # self-contained filter state (same recycled-voice leak as the wire
        # path above): reset any filter letter this osc omits so a partials
        # hit auditioned after a filtered one can't inherit its cutoff.
        for key, letter in (('G', 'filter_type'), ('F', 'filter_freq'),
                            ('R', 'resonance')):
            if key not in present:
                nf.append(key + _fmt(dict(_FILTER_RESET)[letter]))
        out.append(''.join(nf))
    return 'Z'.join(out) + 'Z'


def hit_patch_string(hit_key, overrides=None):
    """AMY patch wire string for one hit ('v0...Zv1...Z'), with sound-design
    overrides applied: tune (semitones, +/-24), decay (0.25..4 time scale),
    level (0..2 gain), snap (0..2 gain on the noise/transient osc)."""
    hit = _hit(hit_key)
    if hit is None:
        raise KeyError(hit_key)
    ov = overrides or {}
    tune = 2.0 ** (max(-24.0, min(24.0, float(ov.get('tune', 0)))) / 12.0)
    decay = max(0.25, min(4.0, float(ov.get('decay', 1.0))))
    level = max(0.0, min(2.0, float(ov.get('level', 1.0)))) * KIT_GAIN
    snap = max(0.0, min(2.0, float(ov.get('snap', 1.0))))
    if 'patch_string' in hit:
        # partials-resynthesized hit: transform the prebuilt string in place
        return _xform_partials(hit['patch_string'], tune, decay, level)
    parts = []
    for i, osc in enumerate(hit['oscs'][:2]):
        o = dict(osc)
        if 'freq' in o and tune != 1.0:
            o['freq'] = _scale_first(o['freq'], tune)
        if 'filter_freq' in o and tune != 1.0:
            o['filter_freq'] = _scale_first(str(o['filter_freq']), tune)
        if decay != 1.0:
            for bp in ('bp0', 'bp1'):
                if bp in o:
                    o[bp] = _scale_times(o[bp], decay)
        g = level * (snap if o.get('wave') == 5 else 1.0)   # 5 = NOISE
        if g != 1.0 and 'amp' in o:
            o['amp'] = _capped_gain(o['amp'], g)
        # make the osc self-contained: fill any omitted filter param with its
        # reset default so a recycled voice can't inherit a prior hit's filter
        for key, dflt in _FILTER_RESET:
            if key not in o:
                o[key] = dflt
        frag = ['v%d' % i]
        for key, letter in _WIRE:
            if key in o:
                frag.append(letter + _fmt(o[key]))
        parts.append(''.join(frag))
    return 'Z'.join(parts) + 'Z'


# ---------------------------------------------------------------------------
# Container kits (upstream drum-kit model, amy patches.h 384-390): the WHOLE
# kit is ONE synth = one voice whose oscs are the hits laid out as consecutive
# blocks, triggered by osc-targeted note maps. Per-hit gain moves out of the
# amp bake into each note map's velocity-scale field (out = amp * vel and
# vel-scale G multiply identically in AMY's log-domain amp combine), so the
# synth-level amp stays free as a kit level -- same scheme as the sampled
# kits' baked io entries.
#
# Trigger contract (one map entry per played note; the template carries one
# Z-separated note-on FRAGMENT per osc that must fire, each tagged i%i + iM%i
# so it lands on this synth's voice and is marked already-mapped -- without
# the iM tag a flags-3 synth would loop the 2nd+ fragment back through the
# note maps):
#   1-osc hit:   one fragment, the osc itself.
#   2-osc hit:   two fragments (tone osc + noise osc). NOT a chained pair:
#                AMY renders a chained osc into its parent's buffer and runs
#                the child's filter over that SUM (amy.c render_osc_wave
#                "stack oscillators"), audibly different from the legacy
#                per-hit voice broadcast, which renders each osc
#                independently -- measured 94% relative-RMS divergence on
#                filtered-noise hits. Two osc-targeted fragments reproduce
#                the broadcast exactly.
#   partials:    one fragment, the w10 parent; partials_note_on drives the
#                w9 children (osc+1..osc+preset, purely parent-relative),
#                and children ignore direct note deltas anyway
#                (wave==PARTIAL skip).
# Anything else -> classify_hit() returns None and the pad keeps a legacy
# per-hit PatchSynth (fallback), which coexists with the container because
# each note map entry is independent.

def classify_hit(hit):
    """'wire' (1-2 plain oscs), 'partials' (w10 parent + matching w9
    children), or None -> the pad must fall back to a per-hit synth."""
    if hit is None:
        return None
    if 'patch_string' in hit:
        frags = [f for f in hit['patch_string'].split('Z') if f]
        if len(frags) < 2:
            return None
        for i, frag in enumerate(frags):
            # strict shape: v<i> in order; frag 0 is the w10 parent whose
            # preset names exactly the child count; children are all w9
            fields = {}
            key, val = None, ''
            for ch in frag:
                if ch.isalpha() and ch in 'vwpfadPABGFR':
                    if key is not None:
                        fields[key] = val
                    key, val = ch, ''
                else:
                    val += ch
            if key is not None:
                fields[key] = val
            try:
                if int(fields.get('v', '-1')) != i:
                    return None
                if i == 0:
                    if fields.get('w') != '10' \
                            or int(fields.get('p', '-1')) != len(frags) - 1:
                        return None
                elif fields.get('w') != '9':
                    return None
            except ValueError:
                return None
        return 'partials'
    oscs = hit.get('oscs')
    if oscs and 1 <= len(oscs) <= 2:
        return 'wire'
    return None


def _container_gain(overrides):
    """(velscale G, tune, decay, snap) for a container hit: G carries
    KIT_GAIN * level (the note map's velocity-scale field); snap stays a
    per-osc amp bake because it only shapes the noise osc."""
    ov = overrides or {}
    tune = 2.0 ** (max(-24.0, min(24.0, float(ov.get('tune', 0)))) / 12.0)
    decay = max(0.25, min(4.0, float(ov.get('decay', 1.0))))
    level = max(0.0, min(2.0, float(ov.get('level', 1.0))))
    snap = max(0.0, min(2.0, float(ov.get('snap', 1.0))))
    return KIT_GAIN * level, tune, decay, snap


def hit_container_oscs(hit_key, overrides, base_osc):
    """One hit as container oscs: (updates, velscale, trig) where updates is
    [(osc_number, {amy.send kwargs})] with design amps (no KIT_GAIN bake --
    the gain rides in velscale) and trig is the osc numbers the note map
    must fire (every wire osc; only the parent for partials). None if the
    hit can't be containerized. Raises KeyError for an unresolvable hit key
    (same as hit_patch_string). The amp cap _AMP_CAP/velscale reproduces the
    legacy per-hit cap: the render-time product amp*velscale can never
    exceed _AMP_CAP (the old fixed-point saturation latch guard)."""
    hit = _hit(hit_key)
    if hit is None:
        raise KeyError(hit_key)
    kind = classify_hit(hit)
    if kind is None:
        return None
    g, tune, decay, snap = _container_gain(overrides)
    amp_cap = (_AMP_CAP / g) if g > 0 else None
    if kind == 'partials':
        ps = _xform_partials(hit['patch_string'], tune, decay, 1.0,
                             amp_cap=(amp_cap if amp_cap is not None
                                      else _AMP_CAP),
                             base_osc=base_osc, pitch=True)
        return _updates_from_patch_string(ps), g, [base_osc]
    updates = []
    for i, osc in enumerate(hit['oscs'][:2]):
        o = dict(osc)
        if 'freq' in o:
            if tune != 1.0:
                o['freq'] = _scale_first(o['freq'], tune)
            # PITCHED oscs track the played note (pack_fill octaves); NOISE
            # (wave 5) has no pitch, so it stays note-independent.
            if o.get('wave') != 5:
                o['freq'] = _pitch_freq(o['freq'])
        if 'filter_freq' in o and tune != 1.0:
            o['filter_freq'] = _scale_first(str(o['filter_freq']), tune)
        if decay != 1.0:
            for bp in ('bp0', 'bp1'):
                if bp in o:
                    o[bp] = _scale_times(o[bp], decay)
        oscgain = snap if o.get('wave') == 5 else 1.0   # 5 = NOISE
        if 'amp' in o and (oscgain != 1.0 or amp_cap is not None):
            o['amp'] = _capped_gain(o['amp'], oscgain,
                                    _AMP_CAP if amp_cap is None else amp_cap)
        for key, dflt in _FILTER_RESET:
            if key not in o:
                o[key] = dflt
        updates.append((base_osc + i, o))
    return updates, g, [osc for osc, _ in updates]


# wire letter per kwarg for container fragments: _WIRE plus the preset
# letter partials strings carry ('p').
_CONTAINER_WIRE = _WIRE + (('preset', 'p'),)
_LETTER_TO_KW = {l: k for k, l in _CONTAINER_WIRE}


def _updates_from_patch_string(ps):
    """[(osc, kwargs)] from a container-ready patch string (partials path).
    Only the closed letter set the deck's own builders emit is understood."""
    updates = []
    for frag in ps.split('Z'):
        if not frag:
            continue
        toks, key, val = [], None, ''
        for ch in frag:
            if ch.isalpha() and ch in 'vwpfadPABGFR':
                if key is not None:
                    toks.append((key, val))
                key, val = ch, ''
            else:
                val += ch
        if key is not None:
            toks.append((key, val))
        osc = None
        kw = {}
        for k, v in toks:
            if k == 'v':
                osc = int(v)
            else:
                kw[_LETTER_TO_KW[k]] = v
        if osc is not None:
            updates.append((osc, kw))
    return updates


def container_fragment(updates):
    """Container patch-string fragment ('v5...Zv6...Z') for one hit's
    updates, letters ordered per _WIRE so envelopes precede amp."""
    parts = []
    for osc, kw in updates:
        frag = ['v%d' % osc]
        for key, letter in _CONTAINER_WIRE:
            if key in kw:
                frag.append(letter + _fmt(kw[key]))
        parts.append(''.join(frag))
    return 'Z'.join(parts) + 'Z'


def container_note_cmd(note, trig, velscale, shift=0):
    """midi_note_cmd payload for one played note: osc-targeted template with
    the per-hit gain in the velocity-scale field (sampled-kit io format:
    note,is_log,min,max,offset,template). One Z-separated fragment per osc
    in trig; each fragment carries i%i (this synth's voice) and iM%i (the
    already-mapped marker -- see the trigger contract above).

    shift (pack_fill's per-key octave offset, semitones) fires the oscs at
    note 60+shift; with the container's pitched freq coefs (_pitch_freq) that
    transposes the hit by `shift`. shift 0 fires n60 -- bit-identical to the
    old single-octave map."""
    fire = 60 + shift
    tmpl = 'Z'.join('v%dn%dl%%vi%%iiM%%i' % (osc, fire) for osc in trig)
    return '%d,0,0,%s,0,%s' % (note, _fmt(velscale), tmpl)


def kit_container(kit_key, hit_overrides=None, hit_swaps=None):
    """Build a whole synth kit as one container patch.
    Returns (patch_string, pads, fallback):
      patch_string  every containerizable hit as consecutive osc blocks
                    ('' if none)
      pads          {note: {'osc', 'nosc', 'trig', 'velscale', 'hit'}}
      fallback      {note: hit_key} pads needing legacy per-hit synths
    Unresolvable hit keys are skipped entirely (KITS-1: bad pad stays
    silent, rest of the kit lives)."""
    ov = hit_overrides or {}
    sw = hit_swaps or {}
    notes = kit_notes(kit_key)
    frags = []
    pads = {}
    fallback = {}
    base = 0
    for note in sorted(notes):
        hit_key = sw.get(note) or sw.get(str(note)) or notes[note]
        o = ov.get(note) or ov.get(str(note))
        try:
            built = hit_container_oscs(hit_key, o, base)
        except (KeyError, ValueError, TypeError):
            continue                    # unresolvable pad: skip, kit lives
        if built is None:
            fallback[note] = hit_key
            continue
        updates, g, trig = built
        frags.append(container_fragment(updates))
        pads[note] = {'osc': base, 'nosc': len(updates), 'trig': trig,
                      'velscale': g, 'hit': hit_key}
        base += len(updates)
    return ''.join(frags), pads, fallback


def audition(hit_key, overrides=None, note=60, vel=1.0, synth=17):
    """Play one hit immediately (editor preview). Uses scratch synth 17 --
    ABOVE the MIDI-channel range: 15 destroyed and re-patched a C-owned
    channel-15 instrument whenever the pad editor auditioned (review F-8).
    (patch_string implies the osc count -- passing oscs_per_voice alongside
    it makes AMY ignore the stored patch.)"""
    import amy
    store_patch(SLOT_AUDITION, hit_patch_string(hit_key, overrides))
    amy.send(synth=synth, num_voices=0)   # release: a re-patch on a live
    amy.send(synth=synth, num_voices=1,   # synth keeps its old config
             patch=SLOT_AUDITION)
    amy.send(synth=synth, note=note, vel=vel)
