#!/usr/bin/env python3
"""Rebake the GeneralUser GM bank (amy/sounds/gm/fonts.bin + amy/src/pcm_gm.h).

See tools/gm/README.md for provenance, the reverse-engineered legacy bake, and
how the restore policy in gm_policy.py was chosen.

Default mode is `surgical`: every preset we are not deliberately fixing is
copied byte-for-byte out of the shipped blob, so the 147 presets we do not touch
are bit-identical rather than "close modulo resampler version".  Only the
presets named in gm_policy.TIER_A / TIER_B are re-derived from the SoundFont.

    python tools/gm/rebake_gm.py --sf2 <path to GeneralUser GS v1.471.sf2>

Add --mode=full to re-derive every name-matched preset from the SF2 instead;
that is useful for measuring resampler drift (--verify prints it) but it is not
what we ship, because it perturbs 147 working presets for no benefit.
"""
import argparse
import collections
import hashlib
import logging
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gm_policy as P

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
DEF_HEADER = os.path.join(REPO, "amy", "src", "pcm_gm.h")
DEF_BLOB = os.path.join(REPO, "amy", "sounds", "gm", "fonts.bin")

# GeneralUser GS v1.471, as mirrored locally (see README: do not hotlink).
SF2_SHA256 = "f45b6b4a68b6bf3d792fcbb6d7de24dc701a0f89c5900a21ef3aaece993b839a"

ROW_RE = re.compile(
    r"\s*/\* \[(\d+)\] preset (\d+) \*/ \{(\d+), (\d+), (\d+), (\d+), (\d+)\}, /\* (.*?) \*/"
)

Entry = collections.namedtuple(
    "Entry", "index preset offset length loopstart loopend midinote name"
)

HEADER_PREAMBLE = """\
// GM SoundFont bank map over the raw int16 blob in sounds/gm/fonts.bin.
// Bank + map taken from Leeman1982/gm2350 (sf2_to_amy.py bake of
// GeneralUser GS et al., 160 presets, 22.05kHz mono). The blob is
// provided at runtime via gm_pcm (mmapped from the `fonts` flash
// partition on ESP32-S3). Only used when GM_FONTS is defined.
// GM program/drum-note -> preset index tables live in amy/gm.py.
//
// Regenerated by tools/gm/rebake_gm.py (see tools/gm/README.md).
// The original bake applied a hard duration cap (22747 frames for looped
// samples, 19247 for one-shots) and dropped the sustain loop whenever the
// cap bound. This rebake restores the real length and the SoundFont loop
// for the melodic presets that were damaged, and copies every other preset
// byte-for-byte from the previous blob.
#ifndef __PCM_GM_H
#define __PCM_GM_H
"""


def parse_header(path):
    rows = []
    for line in open(path):
        m = ROW_RE.match(line)
        if m:
            g = m.groups()
            rows.append(
                Entry(int(g[0]), int(g[1]), int(g[2]), int(g[3]), int(g[4]),
                      int(g[5]), int(g[6]), g[7])
            )
    if not rows:
        raise SystemExit("no pcm_map_t rows parsed from %s" % path)
    base = rows[0].preset - rows[0].index
    return rows, base


def load_sf2(path):
    """Return {name: [sample,...]} and {name: set(sampleModes)} from the SF2."""
    logging.disable(logging.WARNING)  # sf2utils is chatty about one-shot loops
    from sf2utils.sf2parse import Sf2File

    sf2 = Sf2File(open(path, "rb"))
    by_name = collections.defaultdict(list)
    for s in sf2.samples:
        name = getattr(s, "name", None)
        if name:
            by_name[name].append(s)
    modes = collections.defaultdict(set)
    for inst in sf2.instruments:
        for bag in (getattr(inst, "bags", None) or []):
            smp = getattr(bag, "sample", None)
            if smp is None or getattr(smp, "name", None) is None:
                continue
            modes[smp.name].add(getattr(bag, "sample_loop", None))
    return by_name, modes


def pick_sample(by_name, entry):
    """Match a shipped preset to its SF2 sample, disambiguating by root note."""
    cands = by_name.get(entry.name)
    if not cands:
        return None
    for s in cands:
        if getattr(s, "original_pitch", None) == entry.midinote:
            return s
    return cands[0]


def resample(sample, rate):
    """Resample to `rate` and peak-normalize exactly the way the legacy bake did.

    Order matters: normalization is computed over the FULL resampled sample and
    only then is the sample truncated, so a preset whose peak lives in the
    discarded tail ends up quieter than PEAK_NORM. That is what the shipped bank
    does, and matching it is what keeps restored presets at the same level as
    their neighbours.
    """
    import numpy as np
    import resampy

    floaty = np.frombuffer(bytes(sample.raw_sample_data), dtype="int16") / 32768.0
    res = resampy.resample(floaty, sample.sample_rate, rate)
    peak = np.abs(res).max()
    if peak > 0:
        res = res / peak * P.PEAK_NORM
    return np.int16(np.minimum(32767.0, np.maximum(-32768.0, res * 32768.0)))


def sf2_loop_points(sample, rate):
    """Upstream amy.headers.generate_amy_pcm_header()'s loop transplant.

    sf2utils already reports start_loop/end_loop relative to the sample start,
    so this matches upstream verbatim (no cap, no sampleModes check).
    """
    ratio = float(sample.sample_rate) / float(rate)
    return (int(float(sample.start_loop) / ratio),
            int(float(sample.end_loop) / ratio))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sf2", required=True, help="GeneralUser GS v1.471 .sf2 (mirrored locally)")
    ap.add_argument("--old-header", default=DEF_HEADER)
    ap.add_argument("--old-blob", default=DEF_BLOB)
    ap.add_argument("--out-header", default=DEF_HEADER)
    ap.add_argument("--out-blob", default=DEF_BLOB)
    ap.add_argument("--mode", choices=("surgical", "full"), default="surgical")
    ap.add_argument("--rate", type=int, default=P.SAMPLE_RATE)
    ap.add_argument("--budget", type=lambda s: int(s, 0), default=0x4B0000,
                    help="GeneralUser slice size; overshoot is reported, never trimmed")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verify", action="store_true", help="report drift vs the shipped blob")
    args = ap.parse_args()

    import numpy as np

    digest = hashlib.sha256(open(args.sf2, "rb").read()).hexdigest()
    if digest != SF2_SHA256:
        print("WARNING: sf2 sha256 %s\n         expected %s (GeneralUser GS v1.471)"
              % (digest, SF2_SHA256))

    rows, base = parse_header(args.old_header)
    old = np.frombuffer(open(args.old_blob, "rb").read(), dtype="<i2")
    by_name, modes = load_sf2(args.sf2)

    out_audio, out_rows, report = [], [], []
    offset = 0
    for e in rows:
        smp = pick_sample(by_name, e)
        looped = smp is not None and (True in modes.get(e.name, set()))
        action = "copied"
        if smp is not None:
            audio = None
            if args.mode == "full":
                audio = resample(smp, args.rate)
                ls, le = sf2_loop_points(smp, args.rate)
                if looped:
                    length = min(len(audio), le + P.TAIL_FRAMES)
                    loop = P.clamp_loop(length, ls, le) or P.oneshot_loop(length)
                else:
                    length = len(audio)
                    loop = P.oneshot_loop(length)
                action = "rebaked"
            else:
                ls, le = sf2_loop_points(smp, args.rate)
                # plan_entry needs the true resampled length; only pay for the
                # resample when this preset is actually in the restore policy.
                if e.index in P.TIER_A or e.index in P.TIER_B:
                    audio = resample(smp, args.rate)
                    plan = P.plan_entry(e.index, len(audio), ls, le, looped)
                    length, loop = plan[0], (plan[1], plan[2])
                    action = "restored"
                else:
                    plan = None
            if action in ("rebaked", "restored"):
                data = audio[:length]
                if len(data) < length:  # resampler came up short; never pad silently
                    raise SystemExit("preset %d: wanted %d frames, resampler gave %d"
                                     % (e.index, length, len(data)))
                out_audio.append(data)
                out_rows.append(e._replace(offset=offset, length=length,
                                           loopstart=loop[0], loopend=loop[1]))
                report.append((e, out_rows[-1], action, looped))
                offset += length
                continue
        # copy the shipped bytes verbatim
        data = old[e.offset:e.offset + e.length]
        if len(data) != e.length:
            raise SystemExit("preset %d: shipped blob truncated" % e.index)
        out_audio.append(data)
        out_rows.append(e._replace(offset=offset))
        report.append((e, out_rows[-1], action, looped))
        offset += e.length

    blob = np.concatenate(out_audio).astype("<i2")
    total = int(blob.shape[0])
    nbytes = total * 2

    # ---- report -----------------------------------------------------------
    print("=== rebake report (mode=%s, rate=%d) ===" % (args.mode, args.rate))
    print("%-4s %-22s %-9s %8s %8s   %-17s %-17s" %
          ("idx", "name", "action", "old_len", "new_len", "old_loop", "new_loop"))
    changed = 0
    for oe, ne, action, looped in report:
        if oe.length == ne.length and (oe.loopstart, oe.loopend) == (ne.loopstart, ne.loopend):
            continue
        changed += 1
        kind = "ONE-SHOT" if P.is_oneshot(ne.length, ne.loopstart, ne.loopend) else "LOOPED"
        print("%-4d %-22s %-9s %8d %8d   [%6d,%6d] [%6d,%6d] %s" %
              (ne.index, ne.name[:22], action, oe.length, ne.length,
               oe.loopstart, oe.loopend, ne.loopstart, ne.loopend, kind))
    print("\npresets: %d   changed: %d   unchanged: %d" %
          (len(out_rows), changed, len(out_rows) - changed))
    print("bank: %d frames = %d B (%.2f MB)" % (total, nbytes, nbytes / 1e6))
    old_bytes = int(old.shape[0]) * 2
    print("was : %d B (%.2f MB)   delta %+d B (%+.2f MB)"
          % (old_bytes, old_bytes / 1e6, nbytes - old_bytes, (nbytes - old_bytes) / 1e6))
    if nbytes > args.budget:
        print("*** OVER BUDGET: %d B > slice %d B by %d B -- NOT trimming; fix the policy"
              % (nbytes, args.budget, nbytes - args.budget))
    else:
        print("budget: slice 0x%X = %d B -> headroom %d B (%.2f MB)"
              % (args.budget, args.budget, args.budget - nbytes, (args.budget - nbytes) / 1e6))

    # ---- invariants -------------------------------------------------------
    errs = []
    for i, r in enumerate(out_rows):
        if r.loopend > r.length:
            errs.append("preset %d: loopend %d > length %d" % (r.index, r.loopend, r.length))
        if r.loopstart > r.length:
            errs.append("preset %d: loopstart %d > length %d" % (r.index, r.loopstart, r.length))
        exp = 0 if i == 0 else out_rows[i - 1].offset + out_rows[i - 1].length
        if r.offset != exp:
            errs.append("preset %d: offset %d != %d" % (r.index, r.offset, exp))
    if out_rows[-1].offset + out_rows[-1].length != total:
        errs.append("table total != blob length")
    for idx in P.TIER_A:
        r = out_rows[idx]
        if P.is_oneshot(r.length, r.loopstart, r.loopend):
            errs.append("preset %d is Tier A but encodes as a one-shot "
                        "(loop_len=%d length=%d) -- it will NOT sustain"
                        % (idx, r.loopend - r.loopstart, r.length))
    if errs:
        print("\n*** INVARIANT FAILURES ***")
        for e in errs:
            print("  " + e)
        raise SystemExit(1)
    print("invariants OK: contiguous offsets, loopend<=length, Tier A all loop-encoded")

    if args.verify:
        verify(rows, out_rows, old, blob)

    looped_tbl = [0 if P.is_oneshot(r.length, r.loopstart, r.loopend) else 1 for r in out_rows]
    print("\nPRESET_LOOPED changes (apply to deck/gm.py and amy/amy/gm.py):")
    for i, r in enumerate(out_rows):
        was = 0 if P.is_oneshot(rows[i].length, rows[i].loopstart, rows[i].loopend) else 1
        if was != looped_tbl[i]:
            print("  [%3d] %-22s %d -> %d" % (i, r.name[:22], was, looped_tbl[i]))

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return
    write_blob(args.out_blob, blob)
    write_header(args.out_header, out_rows, base, total, args.rate)
    write_looped(looped_tbl)
    print("\nwrote %s (%d B)\nwrote %s" % (args.out_blob, nbytes, args.out_header))


def verify(old_rows, new_rows, old, new):
    """Quantify how far the new blob moved from the shipped one, per preset."""
    import numpy as np
    same = drift = 0
    worst = []
    for o, n in zip(old_rows, new_rows):
        a = old[o.offset:o.offset + o.length].astype(np.int64)
        b = new[n.offset:n.offset + n.length].astype(np.int64)
        k = min(len(a), len(b))
        if len(a) == len(b) and np.array_equal(a, b):
            same += 1
            continue
        drift += 1
        if k:
            d = np.abs(a[:k] - b[:k])
            worst.append((float(d.max()), float(d.mean()), o.name, len(a), len(b)))
    print("\n=== verify vs shipped blob ===")
    print("bit-identical presets: %d / %d" % (same, len(new_rows)))
    print("differing presets    : %d" % drift)
    for mx, mean, name, la, lb in sorted(worst, reverse=True)[:12]:
        print("  %-24s len %6d -> %6d  max|d|=%5.0f mean|d|=%6.2f (of 32768 full scale)"
              % (name[:24], la, lb, mx, mean))


def write_blob(path, blob):
    with open(path, "wb") as f:
        f.write(blob.tobytes())


def write_header(path, rows, base, total, rate):
    with open(path, "w", newline="\n") as p:
        p.write(HEADER_PREAMBLE)
        p.write("#define GM_PRESET_BASE %d\n" % base)
        p.write("#define GM_NUM_SAMPLES %d\n" % len(rows))
        p.write("#define GM_SAMPLE_RATE %d\n" % rate)
        p.write("#define GM_BIN_FRAMES %d\n" % total)
        p.write("const pcm_map_t gm_map[GM_NUM_SAMPLES] PROGMEM = {\n")
        for r in rows:
            p.write("    /* [%d] preset %d */ {%d, %d, %d, %d, %d}, /* %s */\n"
                    % (r.index, base + r.index, r.offset, r.length,
                       r.loopstart, r.loopend, r.midinote, r.name))
        p.write("};\n")
        p.write("#endif // __PCM_GM_H\n")


def looped_block(table):
    """Render the PRESET_LOOPED rows in gm.py's existing format."""
    return "".join("   " + "".join("%4d," % v for v in table[i:i + 16]) + "\n"
                   for i in range(0, len(table), 16))


# deck/gm.py and amy/amy/gm.py are NOT the same file (the deck copy carries full
# UI names and the patch_string helper), but they must agree on PRESET_LOOPED --
# the deck reads it to pick feedback/EG, so a mismatch means a restored preset
# silently stops sustaining. Patch the list in place in both.
GM_PY_PATHS = (
    os.path.join(REPO, "deck", "gm.py"),
    os.path.join(REPO, "amy", "amy", "gm.py"),
)
LOOPED_RE = re.compile(r"(PRESET_LOOPED = \[\n)(?:.*?\n)*?(\])", re.M)


def write_looped(table):
    block = looped_block(table)
    for path in GM_PY_PATHS:
        if not os.path.exists(path):
            print("WARNING: %s missing, not patched" % path)
            continue
        src = open(path).read()
        new, n = LOOPED_RE.subn(lambda m: m.group(1) + block + m.group(2), src, count=1)
        if n != 1:
            raise SystemExit("could not locate PRESET_LOOPED in %s" % path)
        if new != src:
            with open(path, "w", newline="\n") as f:
                f.write(new)
            print("patched PRESET_LOOPED in %s" % path)
        else:
            print("PRESET_LOOPED already current in %s" % path)


if __name__ == "__main__":
    main()
