#!/usr/bin/env python3
"""gen_kitcaps.py -- distil a deck-side peak-cap table for the SAMPLED drum
kits (AMY patches 384-390) from amy/src/patches.h into deck/kitcaps.py.

WHY
---
The sampled Gamma9001 kits bake per-drum velocity-scale (velscale) fields that
run 2.34..13.1. Measured on device at velocity 1.0 (levels/#96 investigation)
those drove AMY output-bus peaks of 2.35..4.79 FS -- i.e. every hit clipped
(>1.0 FS), the loudest by nearly 5x. We want the worst-case bus peak near
1.25 FS (AMY's soft-clip knee; the value the capped synth kits and juno also
sit at), with NO firmware change.

THE CAP MATH (shown here and in the commit)
-------------------------------------------
Ideal: cap each io's velscale at 1.25 / sample_peak (the velscale that makes
THAT sample peak at 1.25 FS), i.e. capped = min(baked, 1.25/sample_peak).
That needs each PCM sample's own peak. Kit 384 (TR-808) uses the in-repo base
bank, but kits 385-390 stream from the external Gamma9001 blob (drums.bin,
mmapped from a flash partition -- NOT a C array in this repo), so per-sample
peaks are NOT derivable here.

Fallback that PRESERVES the kit's balance: scale every baked velscale by ONE
gain chosen so the LOUDEST measured hit lands on target, and every quieter hit
scales proportionally:

    GAIN   = 1.25 FS (target) / 4.79 FS (loudest measured bus peak) = 0.2610
           -> use 0.26 (rounds the loudest hit to 4.79*0.26 = 1.245 FS)
    capped = baked_velscale * 0.26

Every relative level in the kit is retained (it is a uniform scale), and no
hit exceeds ~1.25 FS.

Rejected -- a flat velscale ceiling min(baked, C): to bring the kick
(intrinsic 2.35/3.25 = 0.72 FS per unit velscale) to 1.25 FS needs C = 1.73,
but EVERY baked velscale is >= 2.23, so a 1.73 ceiling collapses the whole kit
onto one level and destroys the mix. A uniform proportional scale is the only
single-parameter fallback that both caps the peak AND keeps the balance.

OUTPUT
------
deck/kitcaps.py: KITCAP_GAIN, and CAPS = {patch: [(note, osc, base, capped)]}
plus entries(patch) -> [(note, midi_note_cmd)] for drums_kit to re-register.

Run from the tulipcc repo root:  python tools/gen_kitcaps.py
"""

import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
# amy is a submodule; a partial worktree may not have it checked out, so allow
# an override (AMY_PATCHES_H) pointing at another checkout's patches.h.
PATCHES_H = os.environ.get('AMY_PATCHES_H',
                           os.path.join(_ROOT, 'amy', 'src', 'patches.h'))
OUT = os.path.join(_ROOT, 'deck', 'kitcaps.py')

SAMPLED_KITS = (384, 385, 386, 387, 388, 389, 390)

# levels/#96 measured (on device, vel 1.0): loudest sampled-kit bus peak.
TARGET_FS = 1.25
LOUDEST_MEASURED_FS = 4.79
GAIN = round(TARGET_FS / LOUDEST_MEASURED_FS, 2)   # 0.26

# io entry as baked in patches.h: ioNOTE,0,0,VELSCALE,0,vOSCnBASEl%vi%i
_IO = re.compile(r'io(\d+),0,0,([0-9.]+),0,v(\d+)n(\d+)l%vi%i')
# a patch table row: /* NUM: name */ "string"
_ROW = re.compile(r'/\*\s*(\d+):[^*]*\*/\s*"((?:[^"\\]|\\.)*)"')


def _fmt(x):
    if abs(x - round(x)) < 0.0005:
        return '%d' % round(x)
    return ('%.3f' % x).rstrip('0').rstrip('.')


def parse_patches(text):
    """{patch_num: patch_string} for the SAMPLED kits."""
    out = {}
    for m in _ROW.finditer(text):
        num = int(m.group(1))
        if num in SAMPLED_KITS:
            out[num] = m.group(2)
    return out


def caps_for(patch_string):
    """[(note, osc, base, capped_velscale)] for one kit's io entries."""
    rows = []
    for note, velscale, osc, base in _IO.findall(patch_string):
        capped = float(velscale) * GAIN
        rows.append((int(note), int(osc), int(base), round(capped, 3)))
    return rows


def build(text):
    patches = parse_patches(text)
    return {p: caps_for(patches[p]) for p in sorted(patches)}


def render(caps):
    lines = []
    lines.append('# kitcaps.py -- GENERATED by tools/gen_kitcaps.py. DO NOT EDIT.')
    lines.append('#')
    lines.append('# Peak-cap table for the SAMPLED drum kits (AMY patches 384-390).')
    lines.append('# Their baked per-drum velscales (2.34..13.1) drove measured bus peaks')
    lines.append('# of 2.35..4.79 FS at vel 1.0 -- every hit clipping. drums_kit re-registers')
    lines.append('# each io note map with velscale scaled by KITCAP_GAIN so the loudest hit')
    lines.append('# lands ~1.25 FS and the rest scale proportionally (balance preserved).')
    lines.append('# GAIN = 1.25 (target FS) / 4.79 (loudest measured bus peak) = %.2f.' % GAIN)
    lines.append('# See tools/gen_kitcaps.py for the full derivation.')
    lines.append('')
    lines.append('KITCAP_GAIN = %s' % GAIN)
    lines.append('')
    lines.append('# {patch: [(played_note, osc, base_note, capped_velscale), ...]}')
    lines.append('CAPS = {')
    for patch in sorted(caps):
        lines.append('    %d: [' % patch)
        row = '        '
        for i, (note, osc, base, capped) in enumerate(caps[patch]):
            tok = '(%d,%d,%d,%s), ' % (note, osc, base, _fmt(capped))
            if len(row) + len(tok) > 78:
                lines.append(row.rstrip())
                row = '        '
            row += tok
        if row.strip():
            lines.append(row.rstrip())
        lines.append('    ],')
    lines.append('}')
    lines.append('')
    lines.append('')
    lines.append('def _fmt(x):')
    lines.append('    if abs(x - round(x)) < 0.0005:')
    lines.append("        return '%d' % round(x)")
    lines.append("    return ('%.3f' % x).rstrip('0').rstrip('.')")
    lines.append('')
    lines.append('')
    lines.append('def entries(patch):')
    lines.append('    """[(note, midi_note_cmd)] capped io note maps for a sampled kit')
    lines.append('    patch, or [] if not a sampled kit. drums_kit re-sends each on the')
    lines.append('    live DrumSynth to override the too-loud baked velscales. Field layout')
    lines.append('    matches the baked entries: note,0,0,cappedscale,0,v<osc>n<base>l%vi%i."""')
    lines.append('    out = []')
    lines.append('    for note, osc, base, capped in CAPS.get(patch, ()):  # noqa')
    lines.append("        out.append((note, '%d,0,0,%s,0,v%dn%dl%%vi%%i'")
    lines.append('                    % (note, _fmt(capped), osc, base)))')
    lines.append('    return out')
    lines.append('')
    return '\n'.join(lines)


def main():
    with open(PATCHES_H, 'r', encoding='utf-8') as f:
        text = f.read()
    caps = build(text)
    if not caps:
        raise SystemExit('no sampled kits parsed from %s' % PATCHES_H)
    out = render(caps)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(out)
    n = sum(len(v) for v in caps.values())
    print('wrote %s: %d kits, %d io entries, GAIN=%s'
          % (OUT, len(caps), n, GAIN))


if __name__ == '__main__':
    main()
